### ISSUE TITLE
Symmetric Linear Quantization

### ISSUE THREAD

**Issue by vinutah** [NervanaSystems/distiller#11]
Hi,

The math for the derivation of y_q under Symmetric Linear Quantization on the page 
https://nervanasystems.github.io/distiller/algo_quantization/index.html seems incorrect.
I am not able to reason out to myself, the scaling of the bias term.

Thanks

**Comment by guyjacob** [comment]
You're right, there is an error in the scale factor of the bias. It should be the reciprocal of the what's in there now. That is, it should be: (q_x * q_w) / q_b.
And actually, the parentheses are wrong as well - the way it is now it implies the bias is added _during_ the accumulation instead of after it.

Will fix - thanks for spotting it!
