### ISSUE TITLE
ssl method doesn't work so well using resnet18 on imagenet

### ISSUE THREAD

**Issue by Yifan122** [NervanaSystems/distiller#116]
Hi thanks for the open source implementation of pruning, it really saves me a lot of time.

But when I try to modify the recipe in the examples/ssl/ssl_filter-removal.yaml to make it work in resnet on imagenet dataset. The result I get is not so well,  the sparsity is around 18%, but acc1 drop from 69% to 51%.

I try to figure out what is going on, but I cannot find the reason.

Does anyone get the same result? Or does someone work very well using ssl filter remove method on resnet18 in imagenet, could u share your recipe with me? I would appreciate that if someone can help me :)

Thanks.

**Comment by nzmora** [comment]
Hi @Yifan122,

Regularization does not work out of the box, unfortunately.  In fact, I found it pretty hard to get to work well (see the comments at the top of a couple of the SSL YAML files) because you need to manually set the regularization strength for each layer.  
How do you do that?  You need to start guessing and experimenting with different values.  It's even harder because the regularization strengths of one layer affect other layers (see my comments at the top of [this](https://github.com/NervanaSystems/distiller/blob/master/examples/ssl/ssl_channels-removal_training.yaml) schedule).  
So I don't think you are doing something wrong necessarily, you just need to experiment more.  But perhaps SSL is not the method you want to use because of its challenges.  This field of model compression is new and changing and there are all kinds of algorithms, but I still haven't found an algorithm or method that works well and is practical for various workloads (classification, segmentation, language, etc.).  If you are a researcher, this is good news because there is lots to do.  If you are an engineer that wants to compress arbitrary networks, this is not so good news.

I hope this helped answer your question.
Cheers
Neta
