### ISSUE TITLE
Support for PyTorch 1.0

### ISSUE THREAD

**Issue by nzmora** [NervanaSystems/distiller#124]
Distiller should support PyTorch 1.0.

Related: https://github.com/NervanaSystems/distiller/issues/85#issuecomment-453733443

**Comment by promach** [comment]
For those computer systems without support for pytorch version 0.40 , you could try this [online colab example](https://colab.research.google.com/drive/1JpTC-22qNIn1DXNaePwocG1snghuJVFr)

**Comment by barrh** [comment]
Pytorch v1 introduces breaking changes, so code following this change will not be backward-compatible. Since this is the case, it's worth _considering_ to overlap this effort with other breaking changes as well:
1. requirements.txt makeover - some packages are very old, e.g. tensorflow==1.7.0
2. Require Python v3.6(/3.7) or later - this will require no immediate code changes, and will open to door to integrate new Python features.
3. API changes (e.g. validation-size=0), etc.

**Comment by barrh** [comment]
Regarding Py3.6, as a user of Distiller, since the bottleneck (for my jobs) is GPUs, I probably won't notice any improvement. As a developer on the other hand, the standard dict is a lot better (no more OrderedDict()!), async is stable API, and there's new formatting. (see relevant doc - https://docs.python.org/3/whatsnew/3.6.html)
Same deal with v3.7, nice new features for developers (debug hook, data classes, dict implementation standardized), but user gets mostly headaches, because it's not as popular yet.

API changes - ADC perhaps?
Also, I feel **print-freq** should be modified or supplemented by prints-per-epoch. I can never tell if print-freq=X is good, too much, or too few, for a given batch-size and dataset.

**Comment by nzmora** [comment]
Release 0.3 with support for PyTorch 1.0.1 is out!  
Cheers
Neta
