### ISSUE TITLE
Query on Quantization of Input batches.

### ISSUE THREAD

**Issue by vinutah** [NervanaSystems/distiller#15]
```
    if args.evaluate:
        if args.quantize:
            model.cpu()
            quantizer = quantization.SymmetricLinearQuantizer(model, 8, 8)
            quantizer.prepare_model()
            model.cuda()
        top1, _, _ = test(test_loader, model, criterion, [pylogger], args.print_freq)
```
I wanted some help understanding the flow for evaluating a quantized model.
From this code, I see that the model parameters and activations are quantized after `quantizer.prepare_model()` but then I was expecting the image batches will be quantized too, before performing inference using `test()`. But I could not find the place where you are attempting to quantize the inputs during forward pass. Once you feed it into the model, `post_quantized_forward()` will take care of quantizing the activations.

I am guessing Its being taken care of in one of the `quantizer` methods. Not exactly sure where.
Could you please elaborate on the flow for quantization of inputs.

**Comment by vinutah** [comment]
Its pretty neat, the pre_quantized_forward() seems to take care of this. 
```
    def pre_quantized_forward(self, input):
        in_scale = symmetric_linear_quantization_scale_factor(self.num_bits_acts, get_tensor_max_abs(input))
        self.current_accum_scale = in_scale * self.w_scale
        if self.has_bias:
            # Re-quantize bias to match x * w scale: b_q' = (in_scale * w_scale / b_scale) * b_q
            self.wrapped_module.bias.data = linear_quantize_clamp(self.base_b_q, self.current_accum_scale / self.b_scale,
                                                                  self.accum_min_q_val, self.accum_max_q_val)
        return [in_scale]
```

**Comment by guyjacob** [comment]
You got it :). Apologies for not answering earlier.

There is one thing I'd like to note, because it seems like a potential misunderstanding: You wrote above "evaluating a quantized model". The flow you're looking at would be more accurately described as "quantizing a model for evaluation". So - a trained model is loaded, quantized, and then evaluated.
In the docs, we refer to this as "direct" quantization - see [here](https://nervanasystems.github.io/distiller/usage/index.html#direct-quantization-without-training).
There's a hidden assumption here, that the model was trained in full-precision. Also note that the quantization method is hard-coded here to [`SymmetricLinearQuantizer`](https://nervanasystems.github.io/distiller/algo_quantization/index.html#symmetric-linear-quantization).

On the other hand - You can apply quantization during training (aka "quantization aware training"). The reasoning behind this is described [here](https://nervanasystems.github.io/distiller/quantization/index.html#training-with-quantization), and the process is described [here](https://nervanasystems.github.io/distiller/schedule/index.html#quantization) and [here](https://nervanasystems.github.io/distiller/design/index.html#training-with-quantization).
If you train a model in this manner, then when you run the trained model with `--evaluate`, you should not use `--quantize`, because the model is already quantized as a result of the training.

As I said, this can be (and probably is) a source for confusion, so I wanted to clarify it here. It is on my to-do list to make these two quantization flows more consistent with each other, I hope to get to it soon.

**Comment by vinutah** [comment]
Sure No Problem. Thanks!

Another follow up question regarding the usage of `self.base_b_q` in the above snippet. 
In particular In [this] line of the method (https://github.com/NervanaSystems/distiller/blob/e7c7d94f167efef36a1f811df4c5fe78f8e6d24b/distiller/quantization/range_linear.py#L133) `base_b_q` does not seem to be an attribute of this class. Or Am I missing something?

**Comment by vinutah** [comment]
I am not very familiar with python function overriding by the child class, but is there a problem ,in 
child class signature : https://github.com/NervanaSystems/distiller/blob/e7c7d94f167efef36a1f811df4c5fe78f8e6d24b/distiller/quantization/range_linear.py#L128 
while parent has https://github.com/NervanaSystems/distiller/blob/e7c7d94f167efef36a1f811df4c5fe78f8e6d24b/distiller/quantization/range_linear.py#L68

**Comment by guyjacob** [comment]
It's not a problem in the sense that Python doesn't prevent you from doing it. From an OO perspective you could say it is problematic, because I can use the parent in a way that I can't use the child (pass multiple arguments to the function).
(There actually is a problem in the code where it could fail, since I didn't override `forward` in the child class and limit it to just one argument. So I could call the child's `forward` with multiple arguments and it will fail when trying to call its `pre_quantized_forward`, which accepts just a single argument. I'll fix that.)

Note that this "pattern" is something borrowed from PyTorch itself - the `forward` function in the base `torch.nn.Module` class allows multiple arguments in the same manner, while child classes limit the number as needed. It looks to me like more of a convenience issue - make it possible to call modules with any number of arguments without having to wrap them in a list/tuple. For example you could imagine and element-wise addition module that can take an arbitrary number of inputs. But, as pointed above, then you can't expect all classes in the hierarchy to behave the same. So you have to be careful with what you're doing.

**Comment by vinutah** [comment]
Thank you for the explanation.
