### ISSUE TITLE
'tuple' object has no attribute 'cuda'

### ISSUE THREAD

**Issue by HKLee2040** [NervanaSystems/distiller#155]
Test the world language model with following command:

python3 main.py --cuda --emsize 1500 --nhid 1500 --dropout 0.65 --tied --compress=../../examples/agp-pruning/word_lang_model.LARGE_70.schedule_agp.yaml --wd=1e-6 --summary=png

It gives me the following error message:

Traceback (most recent call last):
  File "main.py", line 298, in <module>
    draw_lang_model_to_file(model, 'rnn.png', 'wikitext2')
  File "main.py", line 108, in draw_lang_model_to_file
    g = apputils.SummaryGraph(model, dummy_input)
  File "/media/walker/Data/work/distiller/apputils/model_summaries.py", line 99, in __init__
    trace, _ = jit.get_trace_graph(model, dummy_input.cuda())
AttributeError: 'tuple' object has no attribute 'cuda'

Could you help me to solve the problem?

**Comment by nzmora** [comment]
Hi @HKLee2040 ,

You can make a temporary change in apputils/model_summaries.py, line 99, as follows:
-            trace, _ = jit.get_trace_graph(model, dummy_input.cuda())
+            trace, _ = jit.get_trace_graph(model, dummy_input)

I'm not committing this code for now because for the general case (i.e. image classification application), this single change will require some other code changes.  We are freezing 'master' for a few days while we finalize PyTorch 1.0 support.
Cheers,
Nets
