### ISSUE TITLE
Any plan to package distiller

### ISSUE THREAD

**Issue by jiayiliu** [NervanaSystems/distiller#164]
Thank you for open sourcing distiller. 
I am checking whether there is a plan to put it into a self-contained package. 

When I started using distiller, I ran into an import error because in my project folder, I also have a folder named 'models'.  So I think packaging apputils, models, and distiller folders into a coherent package will save a lot of efforts to set up the correct import statements.

I would like to hear your thoughts and would like to help to reformat the package accordingly.

**Comment by nzmora** [comment]
Hi @jiayiliu ,

Yes, we are creating a packaged version of Distiller to be released soon.  We will release it as part of a new Distiller version that supports PyTorch 1.0.
Directory distiller/models will move to distiller/distiller/models so that it becomes part of the distiller package name-space and won't create the name contention that you see.
The branch is https://github.com/NervanaSystems/distiller/tree/release_0.3_pytorch_1.0.0 and we will update the github version.

Cheers,
Neta
