### ISSUE TITLE
I installed and it can't work.Can someone tell me where is wrong? thank you

### ISSUE THREAD

**Issue by xiasiwo123** [NervanaSystems/distiller#214]
I install distiller on windows 10, pytorch 1.0,  I don't have GPU . I input python compress_classifier.py --help 
It get this 
![image](https://user-images.githubusercontent.com/49177441/55459484-464f7500-5622-11e9-9b0e-fca2d4b53b7f.png)

Traceback (most recent call last):
  File "compress_classifier.py", line 776, in <module>
    main()
  File "compress_classifier.py", line 89, in main
    args = parser.get_parser().parse_args()
AttributeError: module 'parser' has no attribute 'get_parser'

Can someone tell me where is wrong? thank you

**Comment by nzmora** [comment]
Hi @xiasiwo123,

Did you remember to install Distiller after you cloned the code?  I think you will see this error when you don't install the package.

I also want to remind that Distiller is only tested on Ubuntu 16.04 LTS (this is in the README), so using Windows may surface issues.  Our support for execution on the CPU is partial, mainly because training on the CPU with PyTorch is very time consuming on many models. 

Cheers,
Neta

**Comment by xiasiwo123** [comment]
> Hi @xiasiwo123,
> 
> Did you remember to install Distiller after you cloned the code? I think you will see this error when you don't install the package.
> 
> I also want to remind that Distiller is only tested on Ubuntu 16.04 LTS (this is in the README), so using Windows may surface issues. Our support for execution on the CPU is partial, mainly because training on the CPU with PyTorch is very time consuming on many models.
> 
> Cheers,
> Neta

Hi nzmora
Thanks for your help. I think I use 'pip install -e .' installed. I will try it on Ubuntu.thank you.

**Comment by Liam-zzZ** [comment]
Rename "parser.py" and change it in "compress_classifier.py"
