### ISSUE TITLE
Query on quantization of Bias

### ISSUE THREAD

**Issue by vinutah** [NervanaSystems/distiller#22]
I am expecting the final model after quantization to have all integers in the range -128 to 127 , for 8 -bit symmetric linear quantization, but when I print out the model parameters I noticed that the bias are still as floats.
so I am currently setting inplace = True in this line https://github.com/NervanaSystems/distiller/blob/2bb9689fe58d196ccbccd3f2f44ac27192eb64e1/distiller/quantization/range_linear.py#L121 . 

At one point we need need to quantize the bias, before writing into the model. Currently I do not see that happening.

**Comment by guyjacob** [comment]
This is caused by a combination of 2 things:

1. We quantize the bias in 2 steps: **`module.base_b_q`** is calculated at initialization time, and the actual **`module.bias`** is re-calculated at each iteration. The reason for this is that the bias needs to be re-scaled to match the scale of the weight * input accumulation, and the scale of this accumulation changes at each iteration, because currently we determine the range of the inputs dynamically (instead of gathering statistics beforehand). See details [here](https://nervanasystems.github.io/distiller/algo_quantization/index.html#symmetric-linear-quantization).
2. By default, we parallelize the model at load time, using PyTorch's `DataParallel`. The way `DataParallel` is implemented, each `forward` call actually works on a copy of the original module, and any changes done to module parameters during forward are not reflected in the original module. So the re-scaling of `base_b_q` into `bias` occurs on the copies as expected (you can check that with print statements or with a debugger), but the original module's `bias` parameters remains float.

When you set `inplace=True` as you mentioned above, it basically means that now in the original module, `bias == base_b_q`, and that's what you should be seeing looking at the checkpoint. But at runtime, it is still re-scaled the same way as described in point 2 above.

Considering we're doing the re-scaling dynamically, seeing the latest re-scaled `bias` isn't that useful anyway. It is only relevant to the last iteration that ran.

**Comment by Luke-WENG** [comment]
Hi Guy, thanks for the detailed explanation.

Given the float parameters and dynamic re-scaling, can the quantized models really reduce memory footprint or save computation during the inference?

**Comment by vinutah** [comment]
@Luke-WENG Really quantized models will certainly reduce memory requirements and computational requirements that is the goal or the purpose of quantizing deep nets in the first place. The are so popular that they are called QNN's . Now, coming to your comment above -- The quantizations implemented in distiller are an emulation (see [here])(https://nervanasystems.github.io/distiller/algo_quantization/index.html) : 

> They are implemented by wrapping the existing PyTorch layers with quantization and de-quantization operations. That is - the computation is done on floating-point tensors, but the values themselves are restricted to integer values. The wrapper is implemented in the RangeLinearQuantParamLayerWrapper class.
All other layers are unaffected and are executed using their original FP32 implementation.

  of the quantization models so do not expect inference improvements using these.  
The purpose here is to study the effect of  quantization schemes on DNNs.
