### ISSUE TITLE
how to save a model,I want to use it for Faster-RCNN

### ISSUE THREAD

**Issue by tongyutyr** [NervanaSystems/distiller#233]
I want to use the model of resnet18 that author offered in model zoo,but the model author offered in the checkpoint.pth.tar has some other values like "epoch" and "optimizer_state_dict",what can I do ?

**Comment by nzmora** [comment]
Hi @tongyutyr,

The checkpoint.pth.tar file format is pickle format, which means that the everything is stored in a kind of dictionary structure.  We store the model parameters in a field named ```state_dict```, according to the PyTorch defacto standard: 

https://github.com/NervanaSystems/distiller/blob/8c5de42cf08e8d32b966a570c207039cb799a528/distiller/apputils/checkpoint.py#L168

This means that you can load our models in other PyTorch applications. 
Note, however, that when you load sparse weights and then train them outside of Distiller, the sparsity will most likely be removed because of the weight update (```w += lr * gradient_w ```).  In Distiller we make sure to maintain the sparsity during these updates.

Cheers
Neta

**Comment by tongyutyr** [comment]
> Hi @tongyutyr,
> 
> The checkpoint.pth.tar file format is pickle format, which means that the everything is stored in a kind of dictionary structure. We store the model parameters in a field named `state_dict`, according to the PyTorch defacto standard:
> 
> [distiller/distiller/apputils/checkpoint.py](https://github.com/NervanaSystems/distiller/blob/8c5de42cf08e8d32b966a570c207039cb799a528/distiller/apputils/checkpoint.py#L168)
> 
> Line 168 in [8c5de42](/NervanaSystems/distiller/commit/8c5de42cf08e8d32b966a570c207039cb799a528)
>  model.load_state_dict(checkpoint['state_dict']) 
> 
> This means that you can load our models in other PyTorch applications.
> Note, however, that when you load sparse weights and then train them outside of Distiller, the sparsity will most likely be removed because of the weight update (`w += lr * gradient_w `). In Distiller we make sure to maintain the sparsity during these updates.
> 
> Cheers
> Neta

thank you,I know how to do that now
