### ISSUE TITLE
Tanks to your great work, unfortunately i have some question to ask

### ISSUE THREAD

**Issue by huyalvchuan** [NervanaSystems/distiller#285]
In somce cases, we need to sparse our own network with particular datasets. But there is no way to do that. could you provide a doc to lead us?

**Comment by nzmora** [comment]
Hi @huyalvchuan,

I'm sorry for the late reply - somehow we missed this issue.
At present we don't have a document describing how to change the datasets, but since we use the standard (bare-bones) PyTorch infrastructure, the procedure for using custom datasets is the same as in any PyTorch application.
You can find some examples here:
- https://pytorch.org/tutorials/beginner/data_loading_tutorial.html
- https://towardsdatascience.com/building-efficient-custom-datasets-in-pytorch-2563b946fd9f

Cheers,
Neta
