### ISSUE TITLE
The problem of post-training quantization 

### ISSUE THREAD

**Issue by hunterkun** [NervanaSystems/distiller#311]
When I try to quantize pretrained model using post-training quantization method, i found it's ok if i set all layers' wights and activations bits to 8 or below.  However, If i only want to quantize weights not activations, i set weights bits to 8 and activations bits to 32. But it fails and acc is collapse. Or I try to set bits of those layers i don't want to quantize to 32 and it also fails again. So I want to ask how I can keep some layers to fp32 which means not quantizing them or only quantizing weights?

**Comment by guyjacob** [comment]
Hi @hunterkun,

Keeping weights as FP32 while quantizing the weights is indeed not supported. But it actually shouldn't be hard to add. Instead of replacing the conv or linear module with a `RangeLinearQuantParamLayerWrapper` as is done now, if a user specifies `bits_activations = None` we could just do a one time, in-place quantize-dequantize operation on the module's parameters and return the module itself without wrapping it.

Any chance you'd like to give that a try? We'd be happy to take a PR implementing that.
Otherwise, we'll try to get to it soon.

P.S. regarding setting `bits_activations = 32`, I'm not sure I understand from what you wrote why is it failing. I would say that if you set `bits_activations` as 32, you'd definitely want to set `bits_accum` to something larger than the default 32. 64 would make sense.

**Comment by hunterkun** [comment]
Thanks for your replay! I got it and i will try to implement it as soon as possible.

**Comment by guyjacob** [comment]
Weights/activations-only post-training quantization added in #439.
