### ISSUE TITLE
Batch norm in filter pruning

### ISSUE THREAD

**Issue by sakishinoda** [NervanaSystems/distiller#330]
The documentation page for filter/channel pruning states:
```
Distiller detects the presence of Batch Normalization layers and adjusts their parameters automatically.
```

I'd like to understand where and how this is done.
Could you explain/add to the documentation or point me to the right part of the code? 

Many thanks!

**Comment by nzmora** [comment]
Hi @sakishinoda ,

This is done in the [thinning code](https://github.com/NervanaSystems/distiller/blob/master/distiller/thinning.py).
Here's an example: https://github.com/NervanaSystems/distiller/blob/6782ccaeae0c02b542c4050d55abc585e34dd1bd/distiller/thinning.py#L335-L336

In this example, we traverse the data-dependency graph and search for BN layers following Convolutions.

Cheers
Neta

**Comment by sakishinoda** [comment]
Thanks Neta - does this mean that the thinning code always needs to be invoked when using a structured pruner?

**Comment by nzmora** [comment]
No - thinning and structure pruning are two related, but separate processes.  Structure pruning will prune channels, filters, rows, etc - i.e. it will place zeros in these structure coefficients.
"Thinning" (which just a name I saw somewhere and adopted it, for lack of a better name) is a process that we sometimes execute _after_ structure-pruning.  It looks for channels/filters that are pruned (all-zero coefficients) and then removes these channels/filters from the network.  So a Convolution layer with 64 output-channels (aka filters), of which 10 output-channels contain all-zero coefficients is transformed to a Convolution layer with 54 output-channels, none of which are all-zero coefficients.  Removing these 10 output channels requires changes in other layers, because of data dependencies, as described in the link you mentioned.
Cheers
Neta

**Comment by sakishinoda** [comment]
OK, I understand - so if a batch norm layer with a bias follows a pruned convolution, when the thinning occurs is the bias term of the removed channels added to the remaining bias terms to maintain the same output as before thinning?

**Comment by nzmora** [comment]
Hi @sakishinoda,
 
We currently remove the biases of the channels we remove, and this indeed means that the pre- and post-thinning networks produce different results -  and potentially this is not optimal.  
I don't know the effect of this - you raise an interesting point :-)

Cheers
Neta

**Comment by nzmora** [comment]
Hi @sakishinoda ,

I'm closing this for now.  If you have any further questions, feel free to reopen or open a new issue.
Thanks
Neta
