### ISSUE TITLE
About Truncated SVD

### ISSUE THREAD

**Issue by wnma3mz** [NervanaSystems/distiller#359]
This is a awesome project that has benefited me a lot. But I have a problem in [truncated_svd.ipynb](https://github.com/NervanaSystems/distiller/blob/master/jupyter/truncated_svd.ipynb), I tried to use the fully connected layer of the Truncated SVD compression model, but the amount of parameters will become larger, causing the model to become larger. 

So, is the role of Truncated SVD here only to speed up the calculation process? But why, in the comment `# See Faster-RCNN: https://github.com/rbgirshick/py-faster-rcnn/blob/master/tools/compress_net.py`, the file name of this link is compress_net, I thought there should be a compression effect. 

I have done something wrong, or I understand the wrong place. Can anyone help me? Grateful！

**Comment by nzmora** [comment]
Hi @wnma3mz ,

I will add an explanation of SVD to the notebook. Meanwhile: [SVD (Singular Value Decomposition)](https://en.wikipedia.org/wiki/Singular_value_decomposition) is an exact factorization of a matrix, W (of shape m x n), to the form USV* (U is m x m, S is m x n, V* is n x n; V* is the transpose of V).  Every matrix has an SVD.

A Linear (fully-connected) layer performs:  y = Wx + b
We can use SVD to rewrite this as: y = (USV*)x + b

So far, we haven’t done any compression, so let’s get to it using Truncated SVD.  TSVD is a method to provide an approximated decomposition of W, in which S has a lower rank.  We want to find an approximation of W that is “good enough” and also accelerates the computation of Wx.  
In the notebook, function ` truncated_svd` uses `l` to denote the lower rank, but I prefer `k` because `l` sometimes looks like `1` (one).  I will change the notebook code.  We choose some k, such that k<m (preferably k<<m).
TSVD is straight-forward: use the largest `k` singular values of `S` and discard the rest (truncate `S`).

After TSVD we have: 
U’ is m x t, S’ is k x k, V’* is k x n.
y ~ (U’S’V’*)x + b
y ~ (U’(S’V’*))x + b

Let’s replace S’V’* with A, because we can pre-compute it once.  A has shape k x n:
y ~ (U’A)x + b
y ~ U’(Ax) + b

Let’s ignore the bias and calculate the number of parameters and FLOPs (floating point operations) for the original y:
-	m*n weights coefficients
-	m*n FLOPs (for batch size = 1)

After TSVD we have:
-	m*k + k*n = k*(m+n) weights coefficients
-	k*n + m*k = k*(m+n) FLOPs (for batch size = 1)

To have compress the weights after TSVD we want: m * n >= k*(m+n)
Let’s rewrite k in terms of m: k = t*m
m * n >= t*m*(m+n)
n >= t*(m+n)
n / (m+n) >= t

In the example notebook: m = 1000; n=2048
So when t=2048/(1000+2048) (that is, k=2048/3048*1000=672), we have equilibrium.  When 0.672>t (i.e. k is smaller than 672), the sum of the size of the weights of A and U’ is smaller than the size of W. 

I hope that helps,
Neta

**Comment by wnma3mz** [comment]
Hi, @nzmora 
Thank you very much for your reply, which has made me very productive.

As you said at the beginning of [truncated_svd.ipynb](https://github.com/NervanaSystems/distiller/blob/master/jupyter/truncated_svd.ipynb), `k` keeps decreasing until it is satisfied `m * n >= k*(m+n)`. Therefore, if we want to achieve the purpose of acceleration and compression, we must meet the condition that `k` is small enough. And after `TSVD`, it will not affect the accuracy of the model excessively.

If `k` does not satisfy `m * n >= k*(m+n),` then performing `TSVD` will be meaningless. That is, there is no effect of accelerating the operation, and there is no effect of compression. Is this correct in my understanding?

**Comment by nzmora** [comment]
Hi @wnma3mz,

Your understanding is correct.  In fact, I would say that to have any *real* benefit you want `m * n >> k*(m+n)`.
Cheers,
Neta

**Comment by wnma3mz** [comment]
Thank you for your patience, I will close this issue. Thank you again.
