### ISSUE TITLE
Cannot quantize F.conv2d?

### ISSUE THREAD

**Issue by le8888e** [NervanaSystems/distiller#364]
Hi,
   I've read your Doc that torch.nn.functional module is not supported for quantization. So if I want to quantize a model which has F.conv2d operation, do I have to change it to nn.conv2d or can 
 I implement replacement_factory[F.con2d]? 

Thank you

**Comment by levzlotnik** [comment]
Hi @le8888e ,

`F.conv2d` is not a module but a **function**, the reason we can't quantize anything that is not registered as `nn.Module` is because we quantize the model by replacing its `model.named_modules()` which only reveals us the registered `nn.Module`s in the model.

In short - you'll have to add `self.conv = nn.Conv2d(...)` layers to the model and call them from `.forward` with `y = self.conv(x)`.

Cheers,
Lev

**Comment by le8888e** [comment]
Hi @levzlotnik,

Thanks for your quick reply. When I replace F.conv2d by self.conv(x) and self.conv = nn.Conv2d(...), there will be a out of memery problem. So are there any other solutions?

Thank you

**Comment by levzlotnik** [comment]
Hi @le8888e,

How come `self.conv = nn.Conv2d(...)` causes an OOM and `F.conv2d` doesn't? in both cases you need somewhere to store the convolution filters (in `nn.Conv2d` these are just the weights).
Does your model use `F.conv2d` from 2 tensors and not from a single input tensor and weight parameters?
That would make sense to me, I would just like to clarify what went wrong.

Lev

**Comment by nzmora** [comment]
Closing due to staleness.  Please re-open if you need further information or assistance.
