### ISSUE TITLE
how to set the final_sparsity in  resnet56_cifar_activation_apoz.yaml  of network trimm

### ISSUE THREAD

**Issue by zhyj3038** [NervanaSystems/distiller#371]
Hi， many thanks for this tool and the  great work. but  I was confused by some details of it.
For example,  in  resnet56_cifar_activation_apoz.yaml ,  the config about pruner is :
``
pruners:
  filter_pruner_60:
    class: ActivationAPoZRankedFilterPruner_AGP
    initial_sparsity : 0.10
    final_sparsity: 0.6
    group_type: Filters
    weights: [
      module.layer1.0.conv1.weight,
      module.layer1.1.conv1.weight,
      module.layer1.2.conv1.weight,
      module.layer1.3.conv1.weight,
      module.layer1.4.conv1.weight,
      module.layer1.5.conv1.weight,
      module.layer1.6.conv1.weight,
      module.layer1.7.conv1.weight,
      module.layer1.8.conv1.weight]

  filter_pruner_50:
    #class: StructuredAutomatedGradualPruner
    class: ActivationAPoZRankedFilterPruner_AGP
    initial_sparsity : 0.10
    final_sparsity: 0.5
    group_type: Filters
    weights: [
      module.layer2.1.conv1.weight,
      module.layer2.2.conv1.weight,
      module.layer2.3.conv1.weight,
      module.layer2.4.conv1.weight,
      module.layer2.6.conv1.weight,
      module.layer2.7.conv1.weight]

  filter_pruner_10:
    class: ActivationAPoZRankedFilterPruner_AGP
    initial_sparsity : 0
    final_sparsity: 0.1
    group_type: Filters
    weights: [module.layer3.1.conv1.weight]

  filter_pruner_30:
    class: ActivationAPoZRankedFilterPruner_AGP
    initial_sparsity : 0.10
    final_sparsity: 0.3
    group_type: Filters
    weights: [
      module.layer3.2.conv1.weight,
      module.layer3.3.conv1.weight,
      module.layer3.5.conv1.weight,
      module.layer3.6.conv1.weight,
      module.layer3.7.conv1.weight,
      module.layer3.8.conv1.weight]
``

 

I have some questions:
1 why we remove module.layer2.5.conv1.weight  ?
2 why we put module.layer3.1.conv1.weight  alone in one group, but other  module.layer3* conv1.weight  in another group ?
3 how we set the final_sparsity of each froup?

**Comment by asti205** [comment]
@zhyj3038:
The general answer to your question is: These are all hyperparameters.

The more specific answers:
1 - Possibly, there is no certain reason. Maybe, it just turned out that not pruning this layer increases the accuracy. However, leaving out a layer means that it will not be quantized. Which layers you quantize, can be seen as hyperparameter

2 - Again, it is a hyperparameter which layer you quantize with which sparsity. Other hyperparameters are the pruner class, here ActivationAPoZRankedFilterPruner_AGP, or the group_type, here Filters. It does not matter if a layer is alone in one group, you just define which sparsity you want for which layer. Maybe it turned out, that the accuracy is higher if you only prune with 10% sparsity for layer module.layer3.1.conv1.weight instead of 30%, as for the other ones (module.layer3* conv1.weight).

3 - This is definitely a hyperparameter. You want to see how far you can go here, to make the model as small as possible but still maintain a high accuracy. For some layers, you can set a higher final_sparsity (which is the targeted sparsity of the layers listed in "weights: [...]"), for some not.

**Comment by levzlotnik** [comment]
Hi,
Closing this since the issue seems resolved and stale. Feel free to reopen.
