### ISSUE TITLE
Saved quantized model won't load if model was quantized with activation stats

### ISSUE THREAD

**Issue by Evan-Zhao** [NervanaSystems/distiller#386]
As title, loading such a model gives the following error (part of file path removed):
```
File "distiller/distiller/apputils/image_classifier.py", line 68, in __init__
    self.start_epoch, self.ending_epoch) = _init_learner(args)
File "distiller/distiller/apputils/image_classifier.py", line 378, in _init_learner
    model, args.resumed_checkpoint_path, model_device=args.device)
File "distiller/distiller/apputils/checkpoint.py", line 237, in load_checkpoint
    (chkpt_file, len(missing_keys)))
ValueError: The loaded checkpoint <checkpoint> is missing <N> state keys
```
Model was quantized with:
```
quantizer = quantization.PostTrainLinearQuantizer(
    model,
    ...
    model_activation_stats=stats_path,
    ...
)
quantizer.prepare_model(distiller.get_dummy_input(input_shape=model.input_shape))
```
and loaded [here](https://github.com/NervanaSystems/distiller/blob/master/distiller/apputils/image_classifier.py#L67)

This issue seems to emerge only when quantization uses model activation stats, in which case [this line](https://github.com/NervanaSystems/distiller/blob/master/distiller/quantization/range_linear.py#L491) is executed instead of line 494-500. Thus the saved state_dict does not contain key 'b_scale' (etc.) which are required on loading.

**Comment by guyjacob** [comment]
This reply is grossly late and probably not relevant to the poster, but for future reference:
The reason for this failure was that at the time this was opened, the activation stats we're not being saved in the data-structure that we use for saving/loading a post-training quantized checkpoint.

A fix for this issue was included in #402 (specifically the addition of [this line](https://github.com/NervanaSystems/distiller/blob/f764a8aa1d8b85ee9cc16c1e50777fdfc1a5273d/distiller/quantization/range_linear.py#L1637)).
