### ISSUE TITLE
Activation collection fails with resnext50

### ISSUE THREAD

**Issue by barrh** [NervanaSystems/distiller#393]
Resnext50 32x4d has been introduces recently via torchvision 0.3.
When collecting activation stats on the model, RuntimeError is raised.

Instruction: `python3 examples/classifier_compression/compres_classifier.py --arch=resnext50_32x4d --pretrained IMAGENET --evaluate --act-stats=test --vs=0`

Error: RuntimeError: The size of tensor a (128) must match the size of tensor b (256) at non-singleton dimension 0

**Comment by nzmora** [comment]
Hi @barrh 
The source of the problem is explained here: https://github.com/NervanaSystems/distiller/blob/7bc2890efa436f02e9cc1ef6939f277b2f0a5e95/distiller/data_loggers/collector.py#L165-L171

You don't see this explanation printed because this `if` statement returns `False`;
https://github.com/NervanaSystems/distiller/blob/7bc2890efa436f02e9cc1ef6939f277b2f0a5e95/distiller/data_loggers/collector.py#L164

Specifically, the problem is in `self.relu` of the `Bottleneck` layer: as you can see the same instance of ReLU is used twice.
```
class Bottleneck(nn.Module):
    expansion = 4

    def __init__(self, inplanes, planes, stride=1, downsample=None, groups=1,
                 base_width=64, dilation=1, norm_layer=None):
        super(Bottleneck, self).__init__()
        if norm_layer is None:
            norm_layer = nn.BatchNorm2d
        width = int(planes * (base_width / 64.)) * groups
        # Both self.conv2 and self.downsample layers downsample the input when stride != 1
        self.conv1 = conv1x1(inplanes, width)
        self.bn1 = norm_layer(width)
        self.conv2 = conv3x3(width, width, stride, groups, dilation)
        self.bn2 = norm_layer(width)
        self.conv3 = conv1x1(width, planes * self.expansion)
        self.bn3 = norm_layer(planes * self.expansion)
        self.relu = nn.ReLU(inplace=True)
        self.downsample = downsample
        self.stride = stride

    def forward(self, x):
        identity = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)
        out = self.relu(out)

        out = self.conv3(out)
        out = self.bn3(out)

        if self.downsample is not None:
            identity = self.downsample(x)

        out += identity
        out = self.relu(out)

        return out
```

When I handled this issue for ResNet50 way back when, I did it by copying TorchVision's resnet.py into Distiller and made the changes to ReLU in that file (https://github.com/NervanaSystems/distiller/blob/master/distiller/models/imagenet/resnet.py).

Today I would suggest a more surgical approach, such as this patch to Mobilenet: https://github.com/NervanaSystems/distiller/blob/7bc2890efa436f02e9cc1ef6939f277b2f0a5e95/distiller/models/__init__.py#L61-L71

I'm not sure when we'll get to fixing this - we are happy to get some help ;-)
Thanks!
Neta

**Comment by barrh** [comment]
This was fixed in: https://github.com/NervanaSystems/distiller/pull/414
Perhaps we should add tests?

**Comment by barrh** [comment]
This was fixed in: https://github.com/NervanaSystems/distiller/pull/414
