### ISSUE TITLE
How are the biases quantized for the LSTM model?

### ISSUE THREAD

**Issue by rdoshi96** [NervanaSystems/distiller#405]
I ran post-training quantization on a simple LSTM model and I am looking at the wrapped module parameters of the quantized model. These parameters contain the quantized weights. I was looking at the weights for each of the LSTM gates and they look properly quantized to 8-bit (the number of bits I specified in post-training quantization). However, when I look through the biases they are integers but are way larger than 8-bit. I was wondering how Distiller quantizes and uses biases.

**Comment by levzlotnik** [comment]
Hi @rdoshi96 ,

By default, we quantize the biases to 32 bits, since it's also the size of the accumulator for the activations. Quantizing the biases to less than that doesn't seem to make sense because you would have to cast it back to `int32` to add it to the accumulator.  
If you use our version of LSTM - i.e. `distiller.modules.DistillerLSTM,DistillerLSTMCell`, which can be easily used with your predefined model of `nn.LSTM`s by a simple call to `distiller.modules.convert_model_to_distiller_lstm(model)`:
https://github.com/NervanaSystems/distiller/blob/9e7ef9874ac4819c98af09e9e6a7d39041745bf7/distiller/modules/rnn.py#L437-L451

You have full control of how you also want to quantize the gates **after** adding in the bias, via `bits_activations[=8 by default]`. 

Let me know if you have more questions.

Lev

**Comment by levzlotnik** [comment]
Hi,
Closing this issue due to staleness. If you have further question, feel free to reopen.
