### ISSUE TITLE
Quantization aware training

### ISSUE THREAD

**Issue by jonathanbonnard** [NervanaSystems/distiller#411]
Hi,
I 'm training a mobilenetv2 on cifar from scratch using 8 bits on weights + activations.(QuantAwareTrainRangeLinearQuantizer)

> --- validate (epoch=64)-----------
10000 samples (512 per mini-batch)
Epoch: [64][   10/   19]    Loss 0.797462    Top1 73.007812    Top5 97.988281
Epoch: [64][   20/   19]    Loss 0.793207    Top1 72.870000    Top5 97.890000
==> Top1: 72.870    Top5: 97.890    Loss: 0.793

`==> Best [Top1: 58.000   Top5: 95.020   Sparsity:0.45   Params: -4419393 on epoch: 12]
Saving checkpoint to: logs/2019.10.28-114149/checkpoint.pth.tar`

As you can see the validation step gives me a 72% top 1 accuracy, but it keeps a 58% top 1 as best checkpoint. 
Is this an issue or something I didn't understand?

**Comment by jonathanbonnard** [comment]
ok, it turns out that the validation step keeps the model with the highest sparsity level. That's not what I expected when using a quantizer

**Comment by nzmora** [comment]
Hi @jonathanbonnard,

Yes, you are correct.  You can see the sorting code in this line: https://github.com/NervanaSystems/distiller/blob/c849a25fd8d8719c1a81d43f85cf831d24f6da37/distiller/apputils/image_classifier.py#L736

This line first sorts the results by `params_nnz_cnt`, followed by `top1`, `top5`, and finally `epoch`.  So the most important ordering feature is `params_nnz_cnt`, which is the count of non-zero (nnz) parameters. This was written from the point-of-view of pruning, and not quantization, and I didn't expect this to influence quantization. However, because there are some zero-coefficients in epoch 12 (in your example above), this sorting scheme breaks the expected behavior.

You can of course change this line to get a different ordering.  
You can also issue a PR with a fix (e.g. when quantization is involved, use a different sorting criteria).
Thanks for pointing out this issue!
Neta

**Comment by jonathanbonnard** [comment]
Thank you @nzmora, this solved my issue.
