### ISSUE TITLE
The pruning doesn't shrink the size of the weight file?

### ISSUE THREAD

**Issue by Ringhu** [NervanaSystems/distiller#416]
Hi, I pruned a MobileNetV2 model following the tutorial [Using Distiller to prune a PyTorch language model](https://nervanasystems.github.io/distiller/tutorial-lang_model.html#using-distiller-to-prune-a-pytorch-language-model), the source code is from [here](https://github.com/kuangliu/pytorch-cifar) and I changed the code to a pruning version. It worked, from the summary I can see the sparsity is what I set in the .yaml file. The question is the weight file kept the same size(9.4MB). Is there anything need to do to shrink the weight file? 

The source code is in [here ](https://github.com/Ringhu/pytorch_cifar_prune)

**Comment by jonathanbonnard** [comment]
hi, 
it depends on the compression method you choose. If the algorithm only set some weights or filters to zero, it won't change the structure of your network. Thus, the size of the model won't change either, all zeros will be encoded as zero in fp32 in the dictionnary. 
I suggest you to look at methods which actually change the network structure accordingly to the pruned parameters(filters, channels or layers).

**Comment by nzmora** [comment]
Hi @Ringhu,

Elaborating on @jonathanbonnard's response: I looked at [your pruning schedule](https://github.com/Ringhu/pytorch_cifar_prune/blob/master/cifar10.yaml) and I see there a mix of element-wise pruning (i.e. pruning of individual weight coefficients) and filter-pruning.  @jonathanbonnard 's comment is correct for `fine_pruner` (I'm referring to the names you used in your pruning schedule).  For more details, see Q1 in the [Distiller FAQ](https://github.com/NervanaSystems/distiller/wiki/Frequently-Asked-Questions-(FAQ)).  It is also true for `fc_pruner`, because Distiller currently only prunes 2D tensor rows/cols, and does not remove them (i.e. *thinning*).  Your `low_pruner`, which is configured to prune filters, will only create zero coefficient in the weights filters, and won't remove filters, because there is no scheduling of the thinning process.  See Q4 in the FAQ.
Finally, I also want to point you to our [tutorial on pruning filters and channels](https://nervanasystems.github.io/distiller/tutorial-struct_pruning.html), which explains the details of filter-pruning.  MobileNet v2 is somewhat "tircky"when it comes to filter/channel removal because of two things:

1. There are data-dependencies due to the skip connections.  I tried to explain this in the [tutorial](https://nervanasystems.github.io/distiller/tutorial-struct_pruning.html#filter-pruning) I linked to above.

2. MobileNet v2 uses depth-wise separable (DWS) convolutions.   DWS convs add further complexity to the data-dependency between the layers.  I did not explain this sort of data-dependency in the tutorial.  Let me know if you need an explanation and I'll try to add detail.

You can create a diagram of MobileNet v2 to see the structure of the computation graph (here's an [example of how to do this yourself](https://github.com/NervanaSystems/distiller/wiki/Distiller-Summary-Reports#png)).

Cheers,
Neta

**Comment by Ringhu** [comment]
Hi @nzmora ，
Thanks for your reply. I still have some questions. In Q4(FAQ), the schedule is :
`extensions:
  net_thinner:
      class: 'FilterRemover'
      thinning_func_str: remove_filters
      arch: 'resnet20_cifar'
      dataset: 'cifar10`
the FilterRemover is indeed used for removing the filters, but as far as i am concerned, it's suitable for the pre-defined network in compress_classifier.py since it mentions the 'arch' and 'dataset' which is also need to be set when running the compress_classifier.py command line. However, I want to use the FilterRemover in my own code, and the reason that I want to prune the MobileNet v2 without compress_classifier.py is a long story. At first I wanted to prune the YOLO using distiller and its weight file didn't shrink, then I thought of this as my mistake when change the source code. So I tried to change another simpler source code to prune a network which is MobileNet v2. So the question is, is FilterRemover and other net thinner methods suitable for non-compress_classifier.py? What other codes should i change when i want to remove the filters or channels and shrink the weight file?
 Moreover, I will be very grateful if you can explain the data-dependency of DWS convs since this structure is found in many networks I have learned.

Thanks,
Ring

**Comment by RizhaoCai** [comment]
> Hi @nzmora ，
> Thanks for your reply. I still have some questions. In Q4(FAQ), the schedule is :
> `extensions: net_thinner: class: 'FilterRemover' thinning_func_str: remove_filters arch: 'resnet20_cifar' dataset: 'cifar10`
> the FilterRemover is indeed used for removing the filters, but as far as i am concerned, it's suitable for the pre-defined network in compress_classifier.py since it mentions the 'arch' and 'dataset' which is also need to be set when running the compress_classifier.py command line. However, I want to use the FilterRemover in my own code, and the reason that I want to prune the MobileNet v2 without compress_classifier.py is a long story. At first I wanted to prune the YOLO using distiller and its weight file didn't shrink, then I thought of this as my mistake when change the source code. So I tried to change another simpler source code to prune a network which is MobileNet v2. So the question is, is FilterRemover and other net thinner methods suitable for non-compress_classifier.py? What other codes should i change when i want to remove the filters or channels and shrink the weight file?
> Moreover, I will be very grateful if you can explain the data-dependency of DWS convs since this structure is found in many networks I have learned.
> 
> Thanks,
> Ring

Hello @Ringhu and @nzmora  

I have the same concern and questions about the 'arch' and 'dataset' as I also want to work on my data with distiller
Have you got an answer to this?

Thanks.
Riz

**Comment by nzmora** [comment]
Hi @Ringhu , @RizhaoCai ,

I hope the answer is still relevant to you.   
![image](https://user-images.githubusercontent.com/31280975/72666515-b5645180-3a1b-11ea-9241-08aab0cb1796.png)
First, this is an example of how to write your own extension of `ScheduledTrainingPolicy` so that you can schedule your own code.  `FilterRemover` is an alias for `StructureRemover`:https://github.com/NervanaSystems/distiller/blob/5532eb90d5316523e25cdea2aa3abefcbb78b344/distiller/thinning.py#L389 The aliasing is for backward compatibility with older scripts.

`StructureRemover` is basically a wrapper around `remove_filters`
https://github.com/NervanaSystems/distiller/blob/5532eb90d5316523e25cdea2aa3abefcbb78b344/distiller/thinning.py#L405

`remove_filters` does not use argument `arch`, but uses `dataset` to create an instance of `SummaryGraph`:
https://github.com/NervanaSystems/distiller/blob/5532eb90d5316523e25cdea2aa3abefcbb78b344/distiller/thinning.py#L86-L96

So, finally, this is the dependency you've asked about.
So why do we create an instance of `SummaryGraph`?  We have a PyTorch `model` and we want to make changes in some if its `nn.module` members.  For example, let's imagine we want to reduce the number of `output_channels` of a Convolution operator module.  This is a complex task described [here](https://nervanasystems.github.io/distiller/tutorial-struct_pruning.html), and it requires us to understand the data-dependencies between layers.  A pytorch model does not provide a means to traverse the data-dependencies, because these are defined in code (in the `forward()` method of `nn.Module` sub-classes), so we need to construct a graph ourselves.  We do this in `SummaryGraph` by performing a forward-pass on the model, exporting to ONNX and then extracting the information from the ONNX computation graph.
That was a detailed explanation, but the bottom line is that currently there is some dependency.  This can be overcome by passing an `input_shape` parameter to `distiller.get_dummy_input`.
I don't plan on making this change in the foreseeable future, but if you want to push a PR, I will review it for merge.

Cheers,
Neta

**Comment by yirs2001** [comment]
Hi @Ringhu , @nzmora,
     Did you shrink the weight size of mobilenetv2?
     I add extensions:
                 net_thinner:
                        class: 'FilterRemover'
                        thinning_func_str: remove_filters
                        arch: mobilenet
                        dataset: cifar100
      Then, I got the error and compression didn't finish.
      any comments?

      tks.
