### ISSUE TITLE
Structure Prunning for MLP or 1-D convolution operation ?

### ISSUE THREAD

**Issue by katakissof** [NervanaSystems/distiller#423]
Hello,
Thank you for your amazing work. 
I would like to ask you if you support any type of structure pruning for 1D convolution (nn.conv1d) operations and if so can you guide me how to run it since I have tried various pruners and all of them where "breaking" somewhere.

Also the if the model is an MLP (having only nn.Linear layers) can it structure pruned ?

Thank you in advance,
Sofoklis

**Comment by nzmora** [comment]
Hi @katakissof,

nn.conv1d is not supported since we did not have a need for it.  What model are you using that has nn.conv1d?

MLPs can be col/row-pruned (e.g. [this example](https://github.com/NervanaSystems/distiller/blob/795590c8869e849c107289bc300585a42f00f178/examples/agp-pruning/resnet20_filters.schedule_agp.yaml#L87-L92)), but we don't yet support "thinning" of col/row-pruned 2D matrices.  This can be added without too much effort, and I might do that (but I'm not sure when).

Cheers,
Neta

**Comment by katakissof** [comment]
Hi @nzmora,
I was performing time series forecasting. It has a similar problem formulation with the Word Language Model but I need to perform **structure pruning** so based to my knowledge of Distiller a LSTM solution is not suitable.

I think it will be really nice if you integrate the conv1D structure pruning operation and the corresponding thinning operation.

Thank you,
Sofoklis
