### ISSUE TITLE
Target budget for distilled model

### ISSUE THREAD

**Issue by simi2525** [NervanaSystems/distiller#430]
Is there currently a way to set a target or desired size of the final model? Either focusing to reduce the actual memory size or number of parameters to a given constraint.

**Comment by levzlotnik** [comment]
Hi @simi2525,

Pruning, especially AGP, works in this fashion - you set the target sparsity (and density=1-sparsity) and train the model to achieve this sparsity. The "size" of the model in this case is the density.  

Lev

**Comment by simi2525** [comment]
Thank you for the reply @levzlotnik.

I know about how sparcity works in pruning techniques, but it is not exactly what I am looking for.

When you prune a CNN model, let's say you remove the x% most unimportant filters, this will not necessarily lead to the removal of x% of the number of parameters you are using. The amount of parameters that actually get removed will vary based on where in the network the pruned filters were located (to what layers they are connected to). So you can reduce the memory usage or parameter count only in a indirect and hard to predict manner.

The same architecture trained with different seeds that gets a 30% pruning, might lead to different final model sizes.

**Comment by nzmora** [comment]
Hi @simi2525,

@levzlotnik is correct in his example, and I think your confusion is because you're thinking of simple threshold-pruning in which weights are pruned by comparing them to a threshold value.  This indeed leads to hard-to-predict sparsity levels.

Distiller also support level-pruning in which you explicitly specify the sparsity level.  E.g. for element-wise (fine-grained) `x%` level-pruning of a tensor, we first compute the L1-norm (or other norm) of all tensor coefficients, then we sort them and remove the lower-ranking `x%` coefficients.

AGP, which @levzlotnik mentioned, simply controls the rate at which this pruning is performed.
Here's some documentation: https://nervanasystems.github.io/distiller/algo_pruning.html

Cheers
Neta
