### ISSUE TITLE
Can distiller reduce the GPU memory of model in inference?  

### ISSUE THREAD

**Issue by wangcc123-dave** [NervanaSystems/distiller#431]

**Comment by levzlotnik** [comment]
Hi @wangcc123-dave ,

Our implementation doesn't reduce memory, but it does simulate the effects of quantization and pruning.  
For pruning - it calculates the zero-masks that are to be applied on the weights, and we're able to permanently disconnect neurons, but pytorch didn't provide a sparse representation until lately, and even now it's only experimental.  
For quantization - even though our simulation of quantization is accurate, the operations are simulated on FP32 representations of integers (i.e. [1.0,2.0,...]). So we don't reduce the memory, but we do plan on exporting the models which were quantized using our API to pytorch1.3 API, thus we will reduce each tensor's memory by a factor of 4 (FP32->int8).  

So stay tuned :)

Lev

**Comment by wangcc123-dave** [comment]
Thanks for your reply！Because our models in the product are over ten,which  occupies much GPU memory in the TITAN V graphics card(12GB).So,compared with model's memory in CPU,it's more important for us to reduce the GPU memory of model in inference.You mean distiller can't do this currently,would you please tell me:
1.Why the operations are simulated on FP32 representations of integers ?
2.When will you publish your quantization to  pytorch1.3 API?
Thank you again.Looking forward to your reply.   :)

Wangcc

**Comment by nzmora** [comment]
Hi @wangcc123-dave,
1. For more details see our [FAQ](https://github.com/NervanaSystems/distiller/wiki/Frequently-Asked-Questions-(FAQ)).
2. We can't commit on a date when we will use the low-level PyTorch 1.3 quantization operations because we've got lots of things going on, but it is pretty high on our task priority list.  
Cheers
Neta

**Comment by wangcc123-dave** [comment]
Ok,thank you for providing so much information for me.
      Best wishes!
      Wangcc

**Comment by wangcc123-dave** [comment]
Another question.Can distiller reduce the GPU memory of model in inference after the compressed checkpoint model is exported to ONNX?

**Comment by levzlotnik** [comment]
By the same logic, since the weights are only zeroed and not converted into sparse representation, nor does pytorch export to the most updated onnx standard (which is constantly updated with new operations), we cannot reduce the memory explicitly. 
As for quantized models, I'm not sure if pytorch quantization API supports export to onnx, however in any case since the our pytorch1.3 quantization API is WIP - for now we cannot export a quantized model to onnx at all.

**Comment by wangcc123-dave** [comment]
'however in any case since the our pytorch1.3 quantization API is WIP' 
Would you please explain what WIP is?

**Comment by levzlotnik** [comment]
> 'however in any case since the our pytorch1.3 quantization API is WIP'
> Would you please explain what WIP is?

**W**ork **I**n **P**rogress

**Comment by wangcc123-dave** [comment]
OK.Thank you so much！
