### ISSUE TITLE
Question on possible relation between object class and shrunk CNN size

### ISSUE THREAD

**Issue by hilman-dayo** [NervanaSystems/distiller#435]
Hello.

First of all, thank you for this awesome library!
I have one question. It is rather more of a general question on the shrinking of the Convolutional Neural Network (CNN).

Will the shrinking of CNN being affected by the object class?
For example, let say I have a CNN architecture and I solely train it to detect vehicle class.
Then, I solely train another same CNN architecture to detect pedestrian class.
Finally, I shrink both of the CNNs with the same methods/techniques.

Will one of it maybe can be shrunk more than the others?
I hope I can get any thought from you guys.
Thanks.

**Comment by levzlotnik** [comment]
Hi @hilman-dayo,

In theory - yes, one of them could be shrunk better than the other.
In an ideal world, you could shrink the model up to a certain limit, and this limit is dictated by the distribution of the data (or rather - by it's entropy).

In practice, if for example you train a classifier on MNIST using some huge CNN, and another classifier on ImageNet (of the same arch of CNN), of course you could shrink the former model a lot more than the latter, the MNIST model would be highly overparameterized. But this is an extreme case.  
It's an interesting question, and I think it's worth researching as a subject on its own.

Lev

**Comment by nzmora** [comment]
Hi @hilman-dayo,

Because in CNNs early layers detect "low-level" features, and deeper layers capture more abstract features, it stands to reason that the early layers activate similar neurons (on average) for all classes, and deeper layers are more tuned to specific classes.  It has been shown in various papers (especially in the field of ["conditional computation"](https://nervanasystems.github.io/distiller/conditional_computation.html) - see this [old list of papers I prepared](https://docs.google.com/spreadsheets/d/1n1xfLbt9QiqOZhSrIOdQNoOLLyozFdhCigdoXxF1cVk/edit?usp=sharing)) that some inputs require less processing than others (e.g. see [early exit](https://nervanasystems.github.io/distiller/algo_earlyexit.html)).  However, this refers to the entire dataset and not to separation by classes.  
A rather new paper [When Does Label Smoothing Help?](https://arxiv.org/abs/1906.02629) shows *"that label smoothing encourages the representations of training examples from the same class to group in tight clusters."* 
An "older" paper [Parsimonious Inference on Convolutional Neural Networks: Learning and applying on-line kernel activation rules](https://arxiv.org/abs/1701.05221) says this: 
> Another interesting fact is that a statistical analysis of the kernel activations of CaffeNet throughout the ILSVRC1012 dataset reveals that images of similar categories tend to use similar kernels. This trend becomes more evident towards the deeper layers, where kernels capture higher-level and more specialized information. Those facts imply that data featuring similar visual attributes, use subnetworks explicitly formed inside the overall trained architecture via the learned activation rules. This enables the forward flow of information in a way which is tailor-made to each sub-class of visual attributes, enabling a parsimonious yet accurate inference process.

So it is likely that the different classes use different parts (subnetworks) of the full network. 
Some classes may use simpler subnetworks compared to other classes, if they have simpler features - but that really depends on your data.

Cheers
Neta

**Comment by hilman-dayo** [comment]
@levzlotnik @nzmora That are some good insights! And thank you for the direction that I can use for my starting point!

**Comment by levzlotnik** [comment]
Hi,
Closing this issue as it seems resolved. Feel free to reopen if there are further questions.
