### ISSUE TITLE
ActivationRankedFilterPruner Problem

### ISSUE THREAD

**Issue by Ringhu** [NervanaSystems/distiller#444]
It seems there are some bugs with ActivationRankedFilterPruner class such as ActivationAPoZRankedFilterPruner,ActivationMeanRankedFilterPruner and so on.when I use these pruners there will always be an error like this:
`ValueError: Could not find  a layer named module.layer2.0.batch_norm1 in the model.
Make sure to use assign_layer_fq_names()`

Can anyone help me about this problem?

**Comment by nzmora** [comment]
Hi @Ringhu ,

The set of pruners that you list above rank and prune **convolutional filters** based on statistics of the activations of these convolution layers.  Therefore, these pruners work on `nn.Conv2d` modules only, while you are passing in to the pruner a BatchNorm module.  That is why you see the error message (which unfortunately does not indicate the true problem). [Here's an example script](https://github.com/NervanaSystems/distiller/blob/b3e80cb1e386500d1747b929d16569b73239bc31/examples/network_trimming/resnet50.filters.activation_apoz_agp.yaml#L117-L149) that uses a scheduled `ActivationAPoZRankedFilterPruner` with convolution modules.

Because these are filter pruners (which only prune filters from convolution modules) it doesn't make sense to parameterize them with any arbitrary module: they would need to somehow (1) understand which convolution module they should prune; (2) understand how to use the activations of the module you give them, in order to prune the convolution module they inferred in (1).

Having said that, a `nn.BatchNorm` module and a `nn.Conv2d` that precedes it are tightly coupled, since `nn.BatchNorm` simply applies an affine transformation to the activations of the `nn.Conv2d` layer.  In such cases it may make sense to parameterize an `ActivationAPoZRankedFilterPruner` with a  `nn.BatchNorm` module and expect it to find the `nn.Conv2d` that precedes the BatchNorm and prune it.  But Distiller currently doesn't support this.

Cheers,
Neta

**Comment by Ringhu** [comment]
@nzmora Thank you for your reply. I change the .yaml file to prune nn.Conv2d module. However, another problem rises. It's same as the previous one:
`ValueError: Could not find a layer named module.layer2.0.relu1 in the model. Make sure to use assign_layer_fq_names()`
I track the error and it's from distiller/pruning/ranked_structure_pruner.py, line 345:
` fq_name = param_name.replace(".conv", ".relu")[:-len(".weight")]`
I don't know why to replace the conv with relu and it does not work.
Anyway I modify the code:
` fq_name = param_name[:-len(".weight")]`
But,unfortunately, there still is an error:
`ValueError: Could not find a layer named module.layer2.0.conv1 in the model. Make sure to use assign_layer_fq_names()`
This time I have no solution anymore...Hope to get your help.
BTW My command is :
`python3 compress_classifier.py --compress=../agp-pruning/resnet20_filters.schedule_agp.yaml --arch resnet20_cifar ../../../data.cifar10/ --epochs=80`

**Comment by nzmora** [comment]
Hi @Ringhu ,

Please send us your schedule (YAML) file.
Also, please try to add a call to `distiller.assign_layer_fq_names(model)` right before [this line of code](https://github.com/NervanaSystems/distiller/blob/48244f3b7ceba689297539cbbea3487f45df4ccd/distiller/pruning/ranked_structures_pruner.py#L346)?
Cheers,
Neta

**Comment by Ringhu** [comment]
My schdule file is simply from [here](https://github.com/NervanaSystems/distiller/blob/master/examples/agp-pruning/resnet20_filters.schedule_agp.yaml) and change [this line](https://github.com/NervanaSystems/distiller/blob/b3e80cb1e386500d1747b929d16569b73239bc31/examples/agp-pruning/resnet20_filters.schedule_agp.yaml#L68) with ActivationAPoZRankedFilterPruner_AGP.
Sorry I don't know what does "add a call" mean. Could you please explain it or show a demonstration?

**Comment by cindybrain** [comment]
Hi, 
have the problem been solved? I meet the similar problem. Thanks

**Comment by nzmora** [comment]
Hi @cindybrain, @Ringhu,

The set of pruners that @Ringhu listed above rank and prune convolutional filters based on statistics of the activations of these convolution layers.  These statistics can be collected from using the training, validation, or test datasets as inputs to the model, and performing forward-passes.
This error is an indication that these statistics have not been collected yet, and asks you to "make sure to use SummaryActivationStatsCollector("apoz_channels")".  
When using `apputils.ClassifierCompressor` this is handled automatically when the `apputils.ClassifierCompressor` is configured to collect statistics.  Stats collection is performed as part of the compression process, when performing forward passes (training, validation, or test). Here's an example of how activation statistics collection is implemented when using the `test` dataset:
https://github.com/NervanaSystems/distiller/blob/9e78723897e6fc0435536a04a47128100341e991/distiller/apputils/image_classifier.py#L654-L660.

When using the sample application `compress_classifier.py`, as in @Ringhu's question, there are three things you need to notice:
1. You need to instruct the application to collect statistics, and you need to tell the application which dataset to use for the collection.  You do that by using the `--act-stats` flag.  The example below collects statistics using the `validation` dataset:
```
 python3 compress_classifier.py --arch resnet20_cifar  $CIFAR10_PATH -p=50 --lr=0.4 --epochs=180 --compress=../agp-pruning/resnet20_filters.schedule_agp.yaml  --resume-from=../ssl/checkpoints/checkpoint_trained_dense.pth.tar --vs=0 --reset-optimizer --gpu=0 --act-stats=valid
```
2. You need to schedule the pruner at epoch 1 or later.  This is because we need to fine-tune for at least one epoch to collect the activation statistics that will be used by the pruning criterion. 

3. By default we only collect stats on ReLU outputs, so we need to exclude `module.layer2.0.downsample.0.weight` from the list (it is a `nn.Conv2d` which is not followed by `nn.ReLU`).  Alternatively, you can change this code line:
https://github.com/NervanaSystems/distiller/blob/ccd11ddbdc08e2ca544f352c66024a8959341830/distiller/data_loggers/collector.py#L222
For example:
```
class SummaryActivationStatsCollector(ActivationStatsCollector):
    def __init__(self, model, stat_name, summary_fn,
                 classes=(torch.nn.ReLU, torch.nn.Conv2d),
                 collector_direction=CollectorDirection.OUT,
                 inputs_consolidate_func=torch.cat):
        super(SummaryActivationStatsCollector, self).__init__(model, stat_name, classes)
        self.summary_fn = summary_fn
        self.collector_direction = collector_direction
        self.inputs_func = inputs_consolidate_func,
```

Finally, here's a working version of the YAML script:
```
pruners:
  low_pruner:
    class: ActivationAPoZRankedFilterPruner_AGP # L1RankedStructureParameterPruner_AGP
    initial_sparsity : 0.10
    final_sparsity: 0.50
    group_type: Filters
    weights: [module.layer2.0.conv1.weight, module.layer2.0.conv2.weight,
              #module.layer2.0.downsample.0.weight,
              module.layer2.1.conv2.weight, module.layer2.2.conv2.weight,
              module.layer2.1.conv1.weight, module.layer2.2.conv1.weight]

  fine_pruner:
    class:  AutomatedGradualPruner
    initial_sparsity : 0.05
    final_sparsity: 0.70
    weights: [module.layer3.1.conv1.weight,  module.layer3.1.conv2.weight,
              module.layer3.2.conv1.weight,  module.layer3.2.conv2.weight]

  fc_pruner:
    class: L1RankedStructureParameterPruner_AGP
    initial_sparsity : 0.05
    final_sparsity: 0.50
    group_type: Rows
    weights: [module.fc.weight]


lr_schedulers:
  pruning_lr:
    class: StepLR
    step_size: 50
    gamma: 0.10

extensions:
  net_thinner:
      class: 'FilterRemover'
      thinning_func_str: remove_filters
      arch: 'resnet20_cifar'
      dataset: 'cifar10'


policies:
  - pruner:
      instance_name : low_pruner
    starting_epoch: 1 # 0
    ending_epoch: 30
    frequency: 2

  - extension:
      instance_name: net_thinner
    epochs: [30]

  - pruner:
      instance_name : fine_pruner
    starting_epoch: 30
    ending_epoch: 50
    frequency: 2

  - pruner:
      instance_name : fc_pruner
    starting_epoch: 30
    ending_epoch: 50
    frequency: 2

  - lr_scheduler:
      instance_name: pruning_lr
    starting_epoch: 0
    ending_epoch: 400
    frequency: 1
```
