### ISSUE TITLE
How to prune the mobilenets?

### ISSUE THREAD

**Issue by Ringhu** [NervanaSystems/distiller#453]
There are some schedules of pruing the mobilenets in distiller. I'm curious about the principle of pruning the mobilenets, or more specifically, pruning the depth-wise seperable convolution? Really appreciate if anyone could expain this.

**Comment by nzmora** [comment]
Hi @Ringhu 

The unique characteristic of DWS convolutions, when it comes to filter pruning, has to do with the thinning procedure, and this is due to data dependencies.

To understand what I mean, let's first review the data dependencies in a "regular convolution" (when groups=1), which I discuss at length [here](https://nervanasystems.github.io/distiller/tutorial-struct_pruning.html).  If A, B and C are all convolution operators connected sequentially (i.e. A ==> B ==> C), then removing a filter from the weights of A, will (1) remove one channel from the activations of A, which means that (2) we need to remove that channel from the weights of B.  If between A and B we have a batch-normalization layer (i.e. A ==> BN ==> B ==> C), then this layer is also affected and we need to remove the parameters of the activation channel that was removed.

So far, nothing new.  Now on to DWS.   Let's imagine that we make the B convolution from above a DWS convolution: i.e. A ==> (B1 ==> B2) ==> C.  B1 is a DW convolution, which means that it has filters of size k*k*1, and groups equal to the number of channels in its input.  B2 is a point-wise convolution.  If we now remove a filter from the weights of A, then (1) we have one less channel in A's output activations (as above); (2) we need to remove that one channel from the weights of B1 (as above).  Nothing new so far. But B1 is a DW convolution so each filter has only one channel - if we remove this single channel, we also remove that filter.  Removing a filter from the weights of B1 means that (3) B1's output has one less channel; which means that (4) we need to remove a channel from the weights of B2.  

DWS have more intricate data dependencies because of the number of groups != 1, and this makes things a bit more complicated.

Hope this helped,
Neta

**Comment by Ringhu** [comment]
Thank you for your reply @nzmora . Maybe I didn't describe my question well. For example, for regular convolution, there are some principle such as Song Han's pruning weights with a threshold, or pruning filters according to the L1norm. So my question is what rules do we follow when we pruning the DWS convolution?

**Comment by dalistarh** [comment]
The DWS convolutions have very little computational load, and therefore it would make very little sense to prune them. 

Best,
Dan
