### ISSUE TITLE
The 8-bit quantization problem of the target detection model (yolov3_ckpt_9.pth)

### ISSUE THREAD

**Issue by Blue-Eagle-10** [NervanaSystems/distiller#478]
Hi@nzmora, 

Excuse me, I have a question, I would like to ask, I want to quantize the target detection model in 8 bits, and its file format is yolov3_ckpt_9.pth, however, the distiller uses the .pth.tar file format and uses the cifar10 classification data set. Can I directly use distiller to perform 8-bit quantization on the target detection model? 
Further, I tested the code and got an error. Excuse me, how can I convert my .pth file? thank you very much!

sincerely,
blueeagle

![2020-02-26 18-16-29屏幕截图](https://user-images.githubusercontent.com/24905967/75335655-c890f980-58c4-11ea-80b7-7e267b18af4d.png)

![2020-02-26 18-17-01屏幕截图](https://user-images.githubusercontent.com/24905967/75335316-47396700-58c4-11ea-837f-5097a45fb5d0.png)

**Comment by guyjacob** [comment]
Hi @Blue-Eagle-10. The `compress_classifier.py` script you're running is for image classification models only. It will not work with an object detection model.

If you look in our [README](https://github.com/NervanaSystems/distiller#getting-started) you can see a summary of what the samples we've implemented.
You'll see that we do have an object detection sample, but **only for pruning**. See [here](https://github.com/NervanaSystems/distiller/tree/master/examples/object_detection_compression).
Also, note that that sample only supports torchvision models out of the box - and YOLO isn't part of torchvision. So if you want to use that, you'll need to modify the code to create your YOLO V3 model before loading the checkpoint.

**Comment by misslibra** [comment]
@guyjacob  I have the same problem. Could you please make a detail example about how to modify the code for yolov3? Thanks a lot !

**Comment by Blue-Eagle-10** [comment]
Hi @guyjacob,
Thank you for your reply! thank you very much!

sincerely,
buleeagle

**Comment by guyjacob** [comment]
@misslibra The following is not specific to yolov3, but to any "custom" model you want to use.
In the object detection sample, you'll see this snippet:
https://github.com/NervanaSystems/distiller/blob/2291fdcc2ea642a98d4e20629acb5a9e2e04b4e6/examples/object_detection_compression/compress_detector.py#L142-L144

This loads the model specified by `args.model` from the `detection` package, which is actually torchvision's detection models.
So you'll need to change that to load your model. Something like:
```python
model = MyModel( ... )
```

Another thing you'll need to make sure is that your model implements the same API for the `forward` function as the torchvision detection models, because that's what this sample expects. When I say "the same API" I mean that your model should accept inputs and return an output in the same format as the torchvision models. You can see an example of what the torchvision models do [here](https://github.com/pytorch/vision/blob/master/torchvision/models/detection/generalized_rcnn.py#L44-L57).

There might be other issues I haven't though of, but these are the two main ones.

**Comment by guyjacob** [comment]
Closing due to staleness. Please re-open if needed.
