### ISSUE TITLE
Pruning all layers

### ISSUE THREAD

**Issue by NadavLightricks** [NervanaSystems/distiller#485]
Hi!

Many pruners require specifications as to which weights I want to prune. Is there a way to specify that I want to prune all the layers? Or alternatively, a way to say "prune all convolution layers"?

For example, if I want to prune a convolutional NN with many layers and I want to use L1RankedStructureParameterPruner, do I really need to find all layer names and make sure I didn't miss anything, or can I say "prune all layers"?

**Comment by nzmora** [comment]
Hi @NadavLightricks ,

Once upon a time Distiller supported this kind of syntax, but I removed it because I wasn't using it.  Pruning all layers to some arbitrary sparsity level is fine if you're doing element-wise pruning, but gets trickier when you're removing channels/filters (e.g. `L1RankedStructureParameterPruner`) on non-sequential models, because of the intricate data dependencies (explained [here](https://nervanasystems.github.io/distiller/tutorial-struct_pruning.html)).  In these cases I needed to be more deliberate when specifying the schedule, so I removed the support for syntax specifying operator classes (although we support regex syntax in quantizer specifications).

Cheers,
Neta
