### ISSUE TITLE
yolov2 and darknet19

### ISSUE THREAD

**Issue by Sunyouteng** [NervanaSystems/distiller#62]
Hello, I wanna prune yolov2's pretrained model, just wanna it to have fewer filters for each layer. But, it is  not in the Torchvision'model set. Does a  model have to be in  Torchvision'model set if I wanna prune it? I studied your documentation for a week, and i did not find a clear way to do that. Yolov2 is first trained on ImageNet then we got Darknet19 model. And then make a little change about darknet19 network, and train it again on object detection dataset and we got yolov2. And I wanna to prune this model. I am new in Pytorch.  Can I do this with Distiller? Can you give me some detailed instructions? If yes, I would like to contribute my work to the nice Distiller.

**Comment by nzmora** [comment]
Hi,

Great to hear that you are considering using Distiller!
Your question is packed, so I'll take it step by step:

1. Sure, you can use Distiller with any network, not just the models that come from TorchVision.  You can see some examples of image classification models that we added [here](https://github.com/NervanaSystems/distiller/tree/master/models).  The code that adds them is [here](https://github.com/NervanaSystems/distiller/blob/master/models/__init__.py).

2. If you add YoLov2, you will be the first to add an object detection model to Distiller, which will help other people!  This might mean a bit of extra work for you, because you might have to adjust the [image classification sample application](https://github.com/NervanaSystems/distiller/blob/master/examples/classifier_compression/compress_classifier.py) to peform object detection.  Therefore, it will probably be easier for you to simply write a new sample application, specifically for object detection, based on your current YoLo application.
When I added a network that learns a language-model I wrote a new sample application (because this is very different from image classification) and I also wrote a [tutorial](https://github.com/NervanaSystems/distiller/wiki/Tutorial:-Using-Distiller-to-prune-a-PyTorch-language-model).  This tutorial should give you a lot of details on how to add a new application.  Basically, to get started you don't need much: you just add some callbacks to your exiting Pytorch YoLo application.

If you need help and guidance, feel free to post more questions and we will try to help.
Cheers,
Neta

**Comment by nzmora** [comment]
Hi Sun,

I think the easiest way to proceed is if you opened a PR on a branch (e.g. call this branch "yolov2") so that I can see (and execute) your code.  

(2) You can attach the YAML file for me to look at.  But sharing all of the code is better, because the problem can be in the code, and not in the YAML.

(3) We currently don't support training on the CPU.  We want to add this feature, but it is low priority (since training most models takes a long time on a CPU compared to a GPU).  Again, if you share your code, I can run it on a GPU to see if it works (but note that I'm going to be in Beijing some of the time and won't be able to help).

(4) Using thinning in epoch=0 and then fine-tuning sounds good.  
Regarding "And for the net_thinner class, how to change the arch: 'resnet56_cifar' and dataset: 'cifar10' for my application?" - this is a good question.  Is the dataset COCO?  I think here we might need to make some changes in the main code to support this (I need to see your code ;-).

Cheers,
Neta

**Comment by Sunyouteng** [comment]
@nzmora 
Hello, friend:
Before I want to use this distiller, I have to get a training program for yolov2. I downloaded it from github, but there is something wrong with it,(maybe i am wrong). After debug the yolov2 pytorch version for a long time, I gave up. And I decided to write a program to implement the algorithm <<PRUNING
FILTERS FOR EFFICIENT CONVNETS>> based on Darknet (C language) and prune the filter physically. And i realy made it yesterday. Thanks for the talking with me. I will go learning disitiller when i take part in the job next year I think. It is happy to learn so much from this open project.
Hope you had a good trip in Beijing. And i am in Shanghai.
Best regards
cheers,
Sun.
