### ISSUE TITLE
No such file or directory: '../../../data.imagenet/train'

### ISSUE THREAD

**Issue by dorian95** [NervanaSystems/distiller#66]
The example in ""Direct" Quantization Without Training" contains the following code 
"python3 compress_classifier.py -a resnet18 ../../../data.imagenet  --pretrained --quantize --evaluate"
When I run it I get: " No such file or directory: '../../../data.imagenet/train'"

**Comment by nzmora** [comment]
Hi @dorian95,

All of our examples assume that you have your data in ../../../data.imagenet (ImageNet) and ../../../data.cifar (CIFAR).  These are relative paths from distiller/examples/classifier_compression.
Of course, you can place your datasets anywhere you want, and just point to them.
Unfortunately we cannot provide the datasets as part of Distiller, due to both size and license issues.

Please look at https://github.com/NervanaSystems/distiller#set-up-the-classification-datasets for an explanation.

Cheers,
Neta

**Comment by nzmora** [comment]
See also: https://github.com/NervanaSystems/distiller/wiki/Use-of-image-classification-datasets
which addresses a different aspect of using ImageNet, that is causing some confusion.
